//GET http://localhost:3000/students?limit=5 HTTP/1.1

POST  http://localhost:3000/teachers/account

//Todos los alumnos que son becados
//GET http://localhost:3000/students?isHolder=true/ HTTP/1.1

//Todos los alumnos mayores de 21 años

//Todos los alumnos y maestros entre los 26 y 28 años

//X numero de profesores
GET http://localhost:3000/teachers/05 HTTP/1.1

//Profesor por id
//GET http://localhost:3000/teachers/08 HTTP/1.1


//Profesores cuyo apellido empiece con una letra en especifico
GET http://localhost:3000/teachers/A HTTP/1.1